server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path= /user/**

      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path= /rating/**

      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path= /hotel/**
  config:
    import: optional:configserver:http://localhost:8085


#eureka:  commented because now we are using config server for fetching the eureka properties from git
#  instance:
#    prefer-ip-address: true

#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#       defaultZone: http://localhost:8761/eureka

# okta configuration
okta:
  oauth2:
    issuer: https://dev-72514421.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa853c39zhAfxMTM5d7
    client-secret: JtWbN8XPdZO26bsMaKH19zYjSEbuMD0eVzKSw64Y
    scopes: openid, profile, email, offline_access
